apiVersion: v1
kind: Pod
metadata:
  name: 48-2019-mcr-pod
spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
      command: ["powershell", "-Command", "Start-Sleep -Seconds 3600"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 0 # Run as Administrator (Windows)
  nodeSelector:
    kubernetes.io/os: windows # Ensure scheduling on Windows nodes
    kubernetes.azure.com/agentpool: win19


##########################   COLD start results:
# # Run 1
# # # Events:
# # #   Type    Reason     Age    From               Message
# # #   ----    ------     ----   ----               -------
# # #   Normal  Scheduled  8m55s  default-scheduler  Successfully assigned winpods-tests/48-2019-mcr-pod to akswin19000004
# # #   Normal  Pulling    8m54s  kubelet            Pulling image "mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019"
# # #   Normal  Pulled     5m44s  kubelet            Successfully pulled image "mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019" in 3m9.681s (3m9.681s including waiting). Image size: 3072610852 bytes.
# # #   Normal  Created    5m44s  kubelet            Created container: windows-container
# # #   Normal  Started    5m26s  kubelet            Started container windows-container
# => Scheduled to Started: 3m 29s / image pull: 3m 10s / Size: ~3.1 GB


##########################   WARM start results:
# # Run 1
# # # Events:
# # #   Type    Reason     Age   From               Message
# # #   ----    ------     ----  ----               -------
# # #   Normal  Scheduled  10s   default-scheduler  Successfully assigned winpods-tests/48-2019-mcr-pod to akswin19000004
# # #   Normal  Pulled     9s    kubelet            Container image "mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019" already present on machine
# # #   Normal  Created    9s    kubelet            Created container: windows-container
# # #   Normal  Started    7s    kubelet            Started container windows-container
# => Scheduled to Started: 3s / image pull: none / Size: ~3.1 GB