apiVersion: v1
kind: Pod
metadata:
  name: 48-2022-acr-pod
spec:
  containers:
    - name: windows-container
      image: acrusw3391575s4halwincont.azurecr.io/run48-svrcore-ltsc2022:latest
      command: ["powershell", "-Command", "Start-Sleep -Seconds 3600"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 0 # Run as Administrator (Windows)
  nodeSelector:
    kubernetes.io/os: windows # Ensure scheduling on Windows nodes
    kubernetes.azure.com/agentpool: win22


##########################   COLD start results:
# # Run 1
# # # Events:
# # #   Type    Reason     Age    From               Message
# # #   ----    ------     ----   ----               -------
# # #   Normal  Scheduled  7m54s  default-scheduler  Successfully assigned winpods-tests/48-2022-acr-pod to akswin22000004
# # #   Normal  Pulling    7m52s  kubelet            Pulling image "acrusw3391575s4halwincont.azurecr.io/run48-svrcore-ltsc2022:latest"
# # #   Normal  Pulled     7m29s  kubelet            Successfully pulled image "acrusw3391575s4halwincont.azurecr.io/run48-svrcore-ltsc2022:latest" in 23.177s (23.177s including waiting). Image size: 2374023537 bytes.
# # #   Normal  Created    7m29s  kubelet            Created container: windows-container
# # #   Normal  Started    7m10s  kubelet            Started container windows-container
# => Scheduled to Started: 44s / image pull: 23s / Size: ~2.4 GB


##########################   WARM start results:
# # Run 1
# # # Events:
# # #   Type    Reason     Age   From               Message
# # #   ----    ------     ----  ----               -------
# # #   Normal  Scheduled  6s    default-scheduler  Successfully assigned winpods-tests/48-2022-acr-pod to akswin22000004
# # #   Normal  Pulling    4s    kubelet            Pulling image "acrusw3391575s4halwincont.azurecr.io/run48-svrcore-ltsc2022:latest"
# # #   Normal  Pulled     4s    kubelet            Successfully pulled image "acrusw3391575s4halwincont.azurecr.io/run48-svrcore-ltsc2022:latest" in 396ms (396ms including waiting). Image size: 2374023537 bytes.
# # #   Normal  Created    4s    kubelet            Created container: windows-container
# # #   Normal  Started    2s    kubelet            Started container windows-container
# => Scheduled to Started: 4s / image pull: <1s / Size: ~2.4 GB