apiVersion: v1
kind: Pod
metadata:
  name: 48-2022-acr-pod
spec:
  containers:
    - name: windows-container
      image: acrusw3391575s4halwincont.azurecr.io/run48-svrcore-ltsc2022:latest
      command: ["powershell", "-Command", "Start-Sleep -Seconds 3600"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 0 # Run as Administrator (Windows)
  nodeSelector:
    kubernetes.io/os: windows # Ensure scheduling on Windows nodes
    kubernetes.azure.com/agentpool: win22


##########################   COLD start results:
# # Run 1


##########################   WARM start results:
# # Run 1
