apiVersion: v1
kind: Pod
metadata:
  name: 48-2022-winiso-pod
spec:
  containers:
    - name: windows-container
      image: acrusw3391575s4halwincont.azurecr.io/hal-dwp/run48-winiso-ltsc2022:latest
      command: ["powershell", "-Command", "Start-Sleep -Seconds 3600"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 0 # Run as Administrator (Windows)
  nodeSelector:
    kubernetes.io/os: windows # Ensure scheduling on Windows nodes
    kubernetes.azure.com/agentpool: win22


# acrusw3391575s4halwincont.azurecr.io/hal-dwp/run48-winiso-ltsc2022:latest image inflated size: 11.28 GB

##########################   ACR PREMIUM pod image pull tests   ##########################

##########################   COLD start results   ##########################
# # Run 1
# Events:
#   Type    Reason     Age   From               Message
#   ----    ------     ----  ----               -------
#   Normal  Scheduled  119s  default-scheduler  Successfully assigned winpods-tests/48-2022-winiso-pod to akswin22000008
#   Normal  Pulling    118s  kubelet            Pulling image "acrusw3391575s4halwincont.azurecr.io/hal-dwp/run48-winiso-ltsc2022:latest"
#   Normal  Pulled     46s   kubelet            Successfully pulled image "acrusw3391575s4halwincont.azurecr.io/hal-dwp/run48-winiso-ltsc2022:latest" in 1m11.203s (1m11.203s including waiting). Image size: 8029386051 bytes.
#   Normal  Created    45s   kubelet            Created container: windows-container
#   Normal  Started    4s    kubelet            Started container windows-container
# => Scheduled to Started: 1m55s / image pull: 1m11s / Size: ~7.47 GB

# # Run 2
# Events:
#   Type    Reason     Age    From               Message
#   ----    ------     ----   ----               -------
#   Normal  Scheduled  3m15s  default-scheduler  Successfully assigned winpods-tests/48-2022-winiso-pod to akswin2200000a
#   Normal  Pulling    3m14s  kubelet            Pulling image "acrusw3391575s4halwincont.azurecr.io/hal-dwp/run48-winiso-ltsc2022:latest"
#   Normal  Pulled     2m6s   kubelet            Successfully pulled image "acrusw3391575s4halwincont.azurecr.io/hal-dwp/run48-winiso-ltsc2022:latest" in 1m8.053s (1m8.053s including waiting). Image size: 8029386051 bytes.
#   Normal  Created    2m4s   kubelet            Created container: windows-container
#   Normal  Started    77s    kubelet            Started container windows-container
# => Scheduled to Started: 1m58s / image pull: 1m8s / Size: ~7.47 GB

# # Run 3

# # Run 4

# # Run 5

# # Run 6

# # Run 7

# # Run 8


##########################   WARM start results   ##########################
# # Run 1

# # Run 2



