apiVersion: v1
kind: Pod
metadata:
  name: 35-2022-mcr-pod
spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022
      command: ["powershell", "-Command", "Start-Sleep -Seconds 3600"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 0 # Run as Administrator (Windows)
  nodeSelector:
    kubernetes.io/os: windows # Ensure scheduling on Windows nodes
    kubernetes.azure.com/agentpool: win22


##########################   COLD start results:
# # Run 1
# Events:
#   Type    Reason     Age    From               Message
#   ----    ------     ----   ----               -------
#   Normal  Scheduled  2m28s  default-scheduler  Successfully assigned win-cont-base/35-2022-mcr-basepod to akswin22000006
#   Normal  Pulling    2m27s  kubelet            Pulling image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022"
#   Normal  Pulled     75s    kubelet            Successfully pulled image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022" in 1m12.454s (1m12.454s including waiting). Image size: 2849747704 bytes.
#   Normal  Created    74s    kubelet            Created container: windows-container
#   Normal  Started    64s    kubelet            Started container windows-container
# =>  Scheduled to Started: 1m 24s / image pull: 1m 12s / Size: ~2.8 GB

# # Run 2
# # # Events:
# # #   Type    Reason     Age   From               Message
# # #   ----    ------     ----  ----               -------
# # #   Normal  Scheduled  2m4s  default-scheduler  Successfully assigned winpods-tests/35-2022-mcr-base to akswin22000002
# # #   Normal  Pulling    2m2s  kubelet            Pulling image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022"
# # #   Normal  Pulled     54s   kubelet            Successfully pulled image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022" in 1m7.998s (1m7.998s including waiting). Image size: 2849747704 bytes.
# # #   Normal  Created    54s   kubelet            Created container: windows-container
# # #   Normal  Started    46s   kubelet            Started container windows-container
# =>  Scheduled to Started: 1m 18s / image pull: 1m 8s / Size: ~2.8 GB


##########################   WARM start results:
# # Run 1
# # # Events:
# # #   Type    Reason     Age   From               Message
# # #   ----    ------     ----  ----               -------
# # #   Normal  Scheduled  15s   default-scheduler  Successfully assigned winpods-tests/35-2022-mcr-basepod to akswin22000002
# # #   Normal  Pulled     13s   kubelet            Container image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022" already present on machine
# # #   Normal  Created    13s   kubelet            Created container: windows-container
# # #   Normal  Started    12s   kubelet            Started container windows-container
# =>  Scheduled to Started: 3s / image pull: none / Size: ~2.8 GB

# # Run 2
# # # Events:
# # #   Type    Reason     Age   From               Message
# # #   ----    ------     ----  ----               -------
# # #   Normal  Scheduled  6s    default-scheduler  Successfully assigned winpods-tests/35-2022-mcr-basepod to akswin22000002
# # #   Normal  Pulled     5s    kubelet            Container image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022" already present on machine
# # #   Normal  Created    5s    kubelet            Created container: windows-container
# # #   Normal  Started    3s    kubelet            Started container windows-container
# =>  Scheduled to Started: 3s / image pull: none / Size: ~2.8 GB