apiVersion: v1
kind: Pod
metadata:
  name: mcr-base-pod-2022-35
  namespace: win-cont-base
spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022
      command: ["powershell", "-Command", "Start-Sleep -Seconds 3600"]
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsUser: 0 # Run as Administrator (Windows)
  nodeSelector:
    kubernetes.io/os: windows # Ensure scheduling on Windows nodes
    kubernetes.azure.com/agentpool: win22


# Events:
#   Type    Reason     Age    From               Message
#   ----    ------     ----   ----               -------
#   Normal  Scheduled  2m28s  default-scheduler  Successfully assigned win-cont-base/mcr-base-pod-2022-35 to akswin22000006
#   Normal  Pulling    2m27s  kubelet            Pulling image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022"
#   Normal  Pulled     75s    kubelet            Successfully pulled image "mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2022" in 1m12.454s (1m12.454s including waiting). Image size: 2849747704 bytes.
#   Normal  Created    74s    kubelet            Created container: windows-container
#   Normal  Started    64s    kubelet            Started container windows-container
